stages:
  - pre_check
  - build_host
  - build_firmware
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: none

check_version:
  stage: pre_check
  image: ${CI_DOCKER_REGISTRY}/esp-env-v6.0:1
  script:
    - export HOSTED_NG_PATH=$PWD/esp_hosted_ng
    - .gitlab/ci/check_hosted_ng_version.sh
  rules:
    - when: always
  tags:
    - build

build_fw_esp32_sdio:
  stage: build_firmware
  image: $CI_DOCKER_REGISTRY/esp-env-v6.0:1
  variables:
    IDF_TARGET: esp32
  script:
    - .gitlab/ci/build_firmware.sh $IDF_TARGET
  rules:
    - changes:
      - esp_hosted_ng/esp/esp_driver/network_adapter/**/*
  tags:
    - build_fw

build_fw_esp32_spi:
  stage: build_firmware
  image: $CI_DOCKER_REGISTRY/esp-env-v6.0:1
  variables:
    IDF_TARGET: esp32
  script:
    - .gitlab/ci/build_firmware.sh $IDF_TARGET spi
  rules:
    - changes:
      - esp_hosted_ng/esp/esp_driver/network_adapter/**/*
  tags:
    - build

build_fw_esp32s2_spi:
  stage: build_firmware
  image: $CI_DOCKER_REGISTRY/esp-env-v6.0:1
  variables:
    IDF_TARGET: esp32s2
  script:
    - .gitlab/ci/build_firmware.sh $IDF_TARGET
  rules:
    - changes:
      - esp_hosted_ng/esp/esp_driver/network_adapter/**/*
  tags:
    - build_fw

build_fw_esp32s3_spi:
  stage: build_firmware
  image: $CI_DOCKER_REGISTRY/esp-env-v6.0:1
  variables:
    IDF_TARGET: esp32s3
  script:
    - .gitlab/ci/build_firmware.sh $IDF_TARGET
  rules:
    - changes:
      - esp_hosted_ng/esp/esp_driver/network_adapter/**/*
  tags:
    - build_fw

build_fw_esp32c2_spi:
  stage: build_firmware
  image: $CI_DOCKER_REGISTRY/esp-env-v6.0:1
  variables:
    IDF_TARGET: esp32c2
  script:
    - .gitlab/ci/build_firmware.sh $IDF_TARGET
  rules:
    - changes:
      - esp_hosted_ng/esp/esp_driver/network_adapter/**/*
  tags:
    - build_fw

build_fw_esp32c3_spi:
  stage: build_firmware
  image: $CI_DOCKER_REGISTRY/esp-env-v6.0:1
  variables:
    IDF_TARGET: esp32c3
  script:
    - .gitlab/ci/build_firmware.sh $IDF_TARGET
  rules:
    - changes:
      - esp_hosted_ng/esp/esp_driver/network_adapter/**/*
  tags:
    - build_fw

build_fw_esp32c6_sdio:
  stage: build_firmware
  image: $CI_DOCKER_REGISTRY/esp-env-v6.0:1
  variables:
    IDF_TARGET: esp32c6
  script:
    - .gitlab/ci/build_firmware.sh $IDF_TARGET
  rules:
    - changes:
      - esp_hosted_ng/esp/esp_driver/network_adapter/**/*
  tags:
    - build_fw

build_fw_esp32c6_spi:
  stage: build_firmware
  image: $CI_DOCKER_REGISTRY/esp-env-v6.0:1
  variables:
    IDF_TARGET: esp32c6
  script:
    - .gitlab/ci/build_firmware.sh $IDF_TARGET
  rules:
    - changes:
      - esp_hosted_ng/esp/esp_driver/network_adapter/**/*
  tags:
    - build_fw

build_fw_esp32c5_spi:
  stage: build_firmware
  image: $CI_DOCKER_REGISTRY/esp-env-v6.0:1
  variables:
    IDF_TARGET: esp32c5
  script:
    - .gitlab/ci/build_firmware.sh $IDF_TARGET spi
  rules:
    - changes:
      - esp_hosted_ng/esp/esp_driver/network_adapter/**/*
  tags:
    - build_fw

build_fw_esp32c5_sdio:
  stage: build_firmware
  image: $CI_DOCKER_REGISTRY/esp-env-v6.0:1
  allow_failure: true
  variables:
    IDF_TARGET: esp32c5
  script:
    - .gitlab/ci/build_firmware.sh $IDF_TARGET sdio
  rules:
    - changes:
      - esp_hosted_ng/esp/esp_driver/network_adapter/**/*
  tags:
    - build_fw

build_host_sdio_linux_6.8.0:
  stage: build_host
  script:
    - cd esp_hosted_ng/host
    - make
  rules:
    - changes:
      - esp_hosted_ng/host/**/*
  tags:
    - hosted_runner_4

build_host_sdio_linux_6.14.0:
  stage: build_host
  script:
    - cd esp_hosted_ng/host
    - make
  rules:
    - changes:
      - esp_hosted_ng/host/**/*
  tags:
    - hosted_runner6

build_host_sdio_linux_5.15.0:
  stage: build_host
  script:
    - cd esp_hosted_ng/host
    - make check
  rules:
    - changes:
      - esp_hosted_ng/host/**/*
  tags:
    - hosted_runner_3

build_host_sdio_linux_5.4.0:
  stage: build_host
  script:
    - cd esp_hosted_ng/host
    - make check
  rules:
    - changes:
      - esp_hosted_ng/host/**/*
  tags:
    - hosted_runner_2

build_host_spi_linux_6.8.0:
  stage: build_host
  script:
    - cd esp_hosted_ng/host
    - make target=spi
  rules:
    - changes:
      - esp_hosted_ng/host/**/*
  tags:
    - hosted_runner_4

build_host_spi_linux_5.15.0:
  stage: build_host
  script:
    - cd esp_hosted_ng/host
    - make check target=spi
  rules:
    - changes:
      - esp_hosted_ng/host/**/*
  tags:
    - hosted_runner_3

build_host_spi_linux_5.4.0:
  stage: build_host
  script:
    - cd esp_hosted_ng/host
    - make check target=spi
  rules:
    - changes:
      - esp_hosted_ng/host/**/*
  tags:
    - hosted_runner_2

deploy_master_github:
  stage: deploy
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  tags:
    - deploy
  only:
    - master
  script:
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - echo -n $GH_KEY > ~/.ssh/id_rsa_base64
      - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - git remote remove github &>/dev/null || true
      - git remote add github git@github.com:espressif/esp-hosted.git
      - git push github "${CI_COMMIT_SHA}:refs/heads/${CI_COMMIT_REF_NAME}"
